name: Push release to ECR

on:
  push:
    tags:
      - v**

env:
  ECR_REPOSITORY: {{ cookiecutter.project_slug }}-backend

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ '{{' }} secrets.ECR_CICD_AWS_ACCESS_KEY_ID {{ '}}' }}
          aws-secret-access-key: ${{ '{{' }} secrets.ECR_CICD_AWS_SECRET_ACCESS_KEY {{ '}}' }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ '{{' }} steps.login-ecr.outputs.registry {{ '}}' }}
          IMAGE_TAG: ${{ '{{' }} github.ref_name {{ '}}' }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
