name: Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: backend

      - name: isort Lint
        uses: isort/isort-action@v1
        with:
          isort-version: 5.13.2
          sort-paths: backend

      - name: black check
        uses: psf/black@stable
        with:
          options: '--check --verbose --exclude=migrations'
          src: backend
