name: Lint commit messages

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install commitlint
        run: npm install --no-save --package-lock=false @commitlint/config-conventional commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: (github.event_name == 'push' && contains(toJSON(github.event.head_commit.message), 'Merge pull request ') == false)
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
