apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: {{ cookiecutter.project_slug }}
      tier: frontend
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
