apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-sandbox-cert
spec:
  secretName: cluster-sandbox-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - api.sandbox.{{ cookiecutter.domain_name }}
  - k8s.sandbox.{{ cookiecutter.domain_name }}
