apiVersion: v1
kind: Namespace
metadata:
  name: {{ cookiecutter.project_dash }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ cookiecutter.project_dash }}-sandbox
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
    - "--log.level=DEBUG"
    - "--certificatesresolvers.letsencrypt.acme.email={{ cookiecutter.email }}"
    - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
